apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: server
        image: apigateway
        resources:
          requests:
              cpu: 100m
              memory: 64Mi
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: ClusterIP
  selector:
    app: apigateway
  ports:
  - port: 5000
    targetPort: 5000

