apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalogdb
spec:
  selector:
    matchLabels:
      app: catalogdb
  serviceName: catalogdb
  replicas: 3
  template:
    metadata:
      labels:
        app: catalogdb
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
      - name: server
        image: mongo:4.4.4
        ports:
        - containerPort: 27017
          name: catalogdb
        volumeMounts:
        - name: catalog-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: catalog-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: catalogdb
# spec:
#   type: ClusterIP
#   selector:
#     app: catalogdb
#   ports:
#   - port: 27017
#     targetPort: 27017
