apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
spec:
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
      - name: server
        image: catalogapi
        resources:
          requests:
              cpu: 100m
              memory: 64Mi
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5020
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi
spec:
  type: ClusterIP
  selector:
    app: catalogapi
  ports:
  - port: 5020
    targetPort: 5020

