apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: editordb
spec:
  selector:
    matchLabels:
      app: editordb
  serviceName: editordb
  replicas: 3
  template:
    metadata:
      labels:
        app: editordb
    spec:
      containers:
      - name: server
        image: mongo:4.4.4
        ports:
        - containerPort: 27017
          name: editordb
        volumeMounts:
        - name: editor-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: editor-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: editordb
spec:
  type: ClusterIP
  selector:
    app: editordb
  ports:
  - port: 27017
    targetPort: 27018
